### PR TITLE
New icons themes.

### PR DESCRIPTION
**Pull request by DAP-DarkneSS**
- Affiliation icons themes:
  - Chevron_Affiliations
  - Space_Invaders_Affiliations
  - Luma_Affiliations
  - Star_Trek_Affiliations
- Status icons themes:
  - Cute
  - Finder
  - Mickey_Mouse
  - toys
  - Woofie
  - Capcom_Fighting_Evolution
  - Mushroom_Mario
  - Super_Mario
- Status icons themes with androids:
  - Androids_Small
  - Androids_Big

### CODE REVIEW

**Comment by 0xd34df00d** [comment]
Хм, похоже, у тебя в Mikey в название директории с иконками вкрался пробел.

**Comment by DAP-DarkneSS** [comment]
Done!

**Comment by DAP-DarkneSS** [comment]
- New chat theme: Eclipse
- Clients_me was improved.
- New icon sets:
  - Simple_status_icons
  - rss_status_icons
  - Dango

**Comment by DAP-DarkneSS** [comment]
- New chat theme: Simply Smooth
- New icon sets:
  - Spotify
  - Flat_Balloons
  - Yoshis_Island
  - iAdium
  - iPhonable
  - Facetime

**Pull request merged**
